title: HQI - Documentation
author: GENCI
logo: image/logo.jpg
url: "www.hqi.fr"
copyright: "2024"

execute:
  execute_notebooks: force

repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

html:
  use_issues_button: true
  use_repository_button: true