title: "HQI - Documentation"
author: GENCI
logo: image/logo.jpg
url: "www.hqi.fr"
copyright: "2024"

execute:
  execute_notebooks: force

#repository:
#  url: https://hqi-france.github.io/Tutoriel/  # Online location of your book
#  path_to_book: docs  # Optional path to your book, relative to the repository root
#  branch: master  # Which branch of the repository should be used when creating links (optional)

html:
  use_repository_button: false
  #announcement: '⚠️Cette documentation est encore en cours de construction⚠️'
  favicon: image/logo.ico
  home_page_in_navbar: true
  use_issues_button: false
  baseurl: https://hqi.fr/