title: "HQI"
author: GENCI
logo: image/logo.jpg
url: "www.hqi-france.github.io"
copyright: "2024 GENCI - All rights reserved"

execute:
  execute_notebooks: 'off'

repository:
 url: https://github.com/HQI-France/Tutoriel
 branch: main
 path_to_book: docs
 

html:
  use_repository_button: False
  use_issues_button: False
  home_page_in_navbar: True
  #announcement: '⚠️Cette documentation est encore en cours de construction⚠️' Possibilité de mettre une annonce
  favicon: image/logo.ico
  baseurl: https://hqi-france.github.io/


# launch_buttons:
#   jupyterhub_url: "" pour lancer les notebooks sur un jupyterhub

sphinx:
  config:
    language: fr
